sbatch submitGCTA 1
sbatch submitGCTA 2
sbatch submitGCTA 3
sbatch submitGCTA 4
sbatch submitGCTA 5
sbatch submitGCTA 6
sbatch submitGCTA 7
sbatch submitGCTA 8
sbatch submitGCTA 9
sbatch submitGCTA 10
sbatch submitGCTA 11
sbatch submitGCTA 12
sbatch submitGCTA 13
sbatch submitGCTA 14
sbatch submitGCTA 15
sbatch submitGCTA 16
sbatch submitGCTA 17
sbatch submitGCTA 18
sbatch submitGCTA 19
sbatch submitGCTA 20
sbatch submitGCTA 21
sbatch submitGCTA 22
